### ISSUE TITLE
Error in contourf for matplotlib version 3.10

### ISSUE THREAD

**Issue by austin-hoover** [Ultraplot/ultraplot#14]
WIth matplotlib==3.10 (ultraplot==0.99.3), `ax.contourf` throws an error:

```python
import numpy as np
import ultraplot as uplt

rng = np.random.default_rng(0)
x = rng.normal(size=(1000, 2))
values, edges = np.histogramdd(x, bins=25)

fig, ax = uplt.subplots()
ax.contourf(edges[0], edges[1], values.T)
```

```
Traceback (most recent call last):
  File "/Users/46h/repo/ultraplot/tests/test_contourf.py", line 9, in <module>
    ax.contourf(values.T)
  File "/Users/46h/repo/ultraplot/ultraplot/internals/inputs.py", line 327, in _preprocess_or_redirect
    return func(self, *args, **kwargs)  # call unbound method
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/46h/repo/ultraplot/ultraplot/axes/plot.py", line 4224, in contourf
    self._fix_patch_edges(m, **edgefix_kw, **contour_kw)  # no-op if not contour_kw
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/46h/repo/ultraplot/ultraplot/axes/plot.py", line 1811, in _fix_patch_edges
    for contour in obj.collections:
                   ^^^^^^^^^^^^^^^
AttributeError: 'QuadContourSet' object has no attribute 'collections'
```

It works with matplotlib==3.9.3. It looks like this collections attribute was removed in matplotlib version 3.8: https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.8.0.html#contourset-is-now-a-single-collection.

**Comment by austin-hoover** [comment]
Removing the for loop below fixes the problem. 

https://github.com/Ultraplot/ultraplot/blob/6b8223a8c3dbb77662bcb8ce0afd38f133dfd0d8/ultraplot/axes/plot.py#L1805-L1814

**Comment by thibaultDrt** [comment]
Tricontourf encounters a similar issue.

This is working 👍 
```python
fig, ax = uplot.subplot()
ax.tricontourf(x, y, z, ec="none")
``` 

This is not working 👎 
```python
fig, ax = uplot.subplot()
ax.tricontourf(x, y, z)
```

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[12], line 2
      [1] fig, ax = uplot.subplot()
----> [2] ax.tricontourf(x, y, z)
      [3] ax.triplot(x, y)

File ~/.venv/lib/python3.11/site-packages/ultraplot/internals/inputs.py:327, in _preprocess_or_redirect.<locals>._decorator.<locals>._preprocess_or_redirect(self, *args, **kwargs)
    [325]     kwargs["color"] = color
    [326] # Call main function
--> [327] return func(self, *args, **kwargs)

File ~/.venv/lib/python3.11/site-packages/ultraplot/axes/plot.py:4446, in PlotAxes.tricontourf(self, x, y, z, **kwargs)
   [4444] m = cm = self._call_native("tricontourf", x, y, z, **kw)
   [4445] m._legend_label = label
-> [4446] self._fix_patch_edges(m, **edgefix_kw, **contour_kw)  # no-op if not contour_kw
   [4447] if contour_kw or labels_kw:
   [4448]     cm = self._fix_contour_edges("tricontour", x, y, z, **kw, **contour_kw)

File ~/.venv/lib/python3.11/site-packages/ultraplot/axes/plot.py:1811, in PlotAxes._fix_patch_edges(obj, edgefix, **kwargs)
   [1808] obj.set_linewidth(linewidth)
   [1809] obj.set_edgecolor("face")
-> [1811] for contour in obj.collections:
   [1812]     contour.set_linestyle("-")
   [1813]     contour.set_linewidth(linewidth)

AttributeError: 'TriContourSet' object has no attribute 'collections'
```

**Comment by cvanelteren** [comment]
We are currently not supporting 3.10. Having said that, the issue you raised was on my todo! I left some comments on the PR you raised. Thanks for the input :D!

**Comment by cvanelteren** [comment]
Fixed and merge in main. See the tag release page for the latest.
