### PR TITLE
Fix contourf for matplotlib 3.10 (fixes Issue #14)

### LINKED ISSUE #14: Error in contourf for matplotlib version 3.10
WIth matplotlib==3.10 (ultraplot==0.99.3), `ax.contourf` throws an error:

```python
import numpy as np
import ultraplot as uplt

rng = np.random.default_rng(0)
x = rng.normal(size=(1000, 2))
values, edges = np.histogramdd(x, bins=25)

fig, ax = uplt.subplots()
ax.contourf(edges[0], edges[1], values.T)
```

```
Traceback (most recent call last):
  File "/Users/46h/repo/ultraplot/tests/test_contourf.py", line 9, in <module>
    ax.contourf(values.T)
  File "/Users/46h/repo/ultraplot/ultraplot/internals/inputs.py", line 327, in _preprocess_or_redirect
    return func(self, *args, **kwargs)  # call unbound method
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/46h/repo/ultraplot/ultraplot/axes/plot.py", line 4224, in contourf
    self._fix_patch_edges(m, **edgefix_kw, **contour_kw)  # no-op if not contour_kw
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/46h/repo/ultraplot/ultraplot/axes/plot.py", line 1811, in _fix_patch_edges
    for contour in obj.collections:
                   ^^^^^^^^^^^^^^^
AttributeError: 'QuadContourSet' object has no attribute 'collections'
```

It works with matplotlib==3.9.3. It looks like this collections attribute was removed in matplotlib version 3.8: https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.8.0.html#contourset-is-now-a-single-collection.

### PR DESCRIPTION
**Pull request by austin-hoover**

### CODE REVIEW

**Review by beckermr — CHANGES_REQUESTED** [review]
We're trying to be careful about changes here since we don't know the code base. This looks like it will break other things and certainly would be wrong for earlier MPL versions.

**Comment by austin-hoover** [comment]
Ah, I forgot about older matplotlib.

**Comment by austin-hoover** [comment]
@beckermr I didn't mean to request another review; clicked accidentally.

**Comment by beckermr** [comment]
You can set this to draft and keep working if you'd like!

**Comment by austin-hoover** [comment]
i don't see the "convert to draft" button under "Reviewers" section. I think you need to respond to the request I accidentally sent?

**Review by beckermr — CHANGES_REQUESTED** [review]
As before...

**Comment by beckermr** [comment]
done!

**Comment by cvanelteren** [comment]
I have this issue actually on my  todos; mpl indicates that this has been indicated from 3.8 onward. As main is compatible with 3.9.x, I think it is safe to move forward with this as long as we tag the version that we drop compatibility with mpl 3.8. However, this PR may be to premature as I haven't tested things on 3.10 yet.

**Comment by cvanelteren** [comment]
To clarify my previous response. Ultraplot itself also indicates some deprecation warnings, I think we should in one swoop clean ultraplot of these things and ensure backwards compatibility and or update them accordingly.

**Comment by cvanelteren** [comment]
Closing in favor of #17
